In [3]:
#1
# 定义一个函数 Print_values，接收三个参数 a, b, c
def Print_values(a, b, c):
    # 当 a 大于 b 时，进入循环
    while a > b:
        # 如果 b 大于 c，执行以下语句
        if b > c:
            # 输出表达式 a + b - 10 * c 的结果
            print(a + b - 10 * c)
        else:
            # 如果 a 大于 c，执行以下语句
            if a > c:
                # 输出表达式 a + c - 10 * b 的结果
                print(a + c - 10 * b)
            else:
                # 否则，输出表达式 c + a - 10 * b 的结果
                print(c + a - 10 * b)
    # 如果 while 条件不满足（即 a <= b），执行 else 块
    else:
        # 如果 b 大于 c，输出字符串 'END'
        if b > c:
            print('END')
        else:
            # 否则，输出表达式 c + b - 10 * a 的结果
            print(c + b - 10 * a)

# 调用函数，传入参数 a=5, b=15, c=10
Print_values(5, 15, 10)

END


In [5]:
#2
# 导入 math 模块，用于使用 math.ceil 函数进行向上取整
import math
# 定义主函数 Cal，接收一个整数列表 N
def Cal(N):
    # 定义内部函数 F(x)，用于计算连续取整函数 F(x) = F(ceil(x/3)) + 2x，且 F(1) = 1
    def F(x):
        # 基础情况：F(1) = 1
        if x == 1:             
            return 1
        # 递归调用：对 x 进行向上取整除以 3，然后加上 2x
        return F(math.ceil(x / 3)) + 2 * x
    # 输入验证：确保列表中的每个元素都是正整数
    for x in N:
        # 如果不是整数或小于等于 0
        if int(x) != x or x <= 0:
            # 提示错误信息并返回 None
            return print("Given a list with N positive integers please")  
    # 如果所有输入合法，返回每个元素对应的 F(x) 结果列表
    return [F(x) for x in N]
print(Cal([1, 2, 3]))

[1, 5, 7]


In [7]:
#3.1
# 定义函数：计算掷 10 个骰子总和为 x 的所有可能组合数
def Find_number_of_ways(x):
    # 初始化计数器，用于统计总和为 x 的组合数
    plan = 0
    # 所有可能的组合总数（每个骰子有 6 种可能，共 10 个骰子）
    total_combinations = 6 ** 10  
    # 当前已遍历的组合数，用于进度显示
    current = 0  
    # 使用 10 层嵌套循环，枚举每个骰子的点数（从 1 到 6）
    for d1 in range(1, 7):
        for d2 in range(1, 7):
            for d3 in range(1, 7):
                for d4 in range(1, 7):
                    for d5 in range(1, 7):
                        for d6 in range(1, 7):
                            for d7 in range(1, 7):
                                for d8 in range(1, 7):
                                    for d9 in range(1, 7):
                                        for d10 in range(1, 7):
                                            # 每枚举一个组合，计数器加一
                                            current += 1  
                                            # 每处理 100 万个组合，打印一次进度百分比
                                            if current % 1000000 == 0:
                                                print(f"已完成：{current / total_combinations:.1%}")
                                            # 计算当前组合的总和
                                            total = sum([d1, d2, d3, d4, d5, d6, d7, d8, d9, d10])
                                            # 如果总和等于目标值 x，则符合条件，计数器加一
                                            if total == x:
                                                plan += 1
    # 打印最终结果：总和为 x 的组合数
    print(f"10个骰子总和为{x}的方式数：{plan}")
Find_number_of_ways(45)

已完成：1.7%
已完成：3.3%
已完成：5.0%
已完成：6.6%
已完成：8.3%
已完成：9.9%
已完成：11.6%
已完成：13.2%
已完成：14.9%
已完成：16.5%
已完成：18.2%
已完成：19.8%
已完成：21.5%
已完成：23.2%
已完成：24.8%
已完成：26.5%
已完成：28.1%
已完成：29.8%
已完成：31.4%
已完成：33.1%
已完成：34.7%
已完成：36.4%
已完成：38.0%
已完成：39.7%
已完成：41.3%
已完成：43.0%
已完成：44.7%
已完成：46.3%
已完成：48.0%
已完成：49.6%
已完成：51.3%
已完成：52.9%
已完成：54.6%
已完成：56.2%
已完成：57.9%
已完成：59.5%
已完成：61.2%
已完成：62.8%
已完成：64.5%
已完成：66.2%
已完成：67.8%
已完成：69.5%
已完成：71.1%
已完成：72.8%
已完成：74.4%
已完成：76.1%
已完成：77.7%
已完成：79.4%
已完成：81.0%
已完成：82.7%
已完成：84.3%
已完成：86.0%
已完成：87.7%
已完成：89.3%
已完成：91.0%
已完成：92.6%
已完成：94.3%
已完成：95.9%
已完成：97.6%
已完成：99.2%
10个骰子总和为45的方式数：831204


In [ ]:
#3.2
# 定义函数：计算掷 10 个骰子总和为 x 的所有可能组合数
def Find_number_of_ways(x):
    # 初始化计数器，用于统计总和为 x 的组合数
    plan = 0
    # 所有可能的组合总数（每个骰子有 6 种可能，共 10 个骰子）
    total_combinations = 6 ** 10  
    # 当前已遍历的组合数，用于进度显示
    current = 0  
    # 使用 10 层嵌套循环，枚举每个骰子的点数（从 1 到 6）
    for d1 in range(1, 7):
        for d2 in range(1, 7):
            for d3 in range(1, 7):
                for d4 in range(1, 7):
                    for d5 in range(1, 7):
                        for d6 in range(1, 7):
                            for d7 in range(1, 7):
                                for d8 in range(1, 7):
                                    for d9 in range(1, 7):
                                        for d10 in range(1, 7):
                                            # 每枚举一个组合，计数器加一
                                            current += 1  
                                            # 每处理 100 万个组合，打印一次进度百分比
                                            if current % 1000000 == 0:
                                                print(f"已完成：{current / total_combinations:.1%}")
                                            # 计算当前组合的总和
                                            total = sum([d1, d2, d3, d4, d5, d6, d7, d8, d9, d10])
                                            # 如果总和等于目标值 x，则符合条件，计数器加一
                                            if total == x:
                                                plan += 1
    # 打印最终结果：总和为 x 的组合数
    print(f"10个骰子总和为{x}的方式数：{plan}")
# 初始化列表，用于存储每个 x（从 10 到 60）对应的组合数
Number_of_ways = []
# 遍历所有可能的总和 x，从 10 到 60（因为每个骰子最小是 1，最大是 6）
for x in range(10, 61):
    # 调用函数，计算总和为 x 的组合数
    ways = Find_number_of_ways(x)
    # 将结果添加到列表中
    Number_of_ways.append(ways)    

# 找出组合数最多的那个总和
max_ways = max(Number_of_ways) # 最大的组合数
# 对应的总和 x（加上偏移量 10）
max_x = Number_of_ways.index(max_ways) + 10  
# 打印结果：哪个总和对应最多的组合方式
print(f"Maximum number of ways occurs at x = {max_x}")

In [8]:
#4.1
import random
# 导入绘图库，用于绘制趋势图
import matplotlib.pyplot as plt
# 定义函数：生成一个长度为 N 的整数数组，元素在 1 到 10 之间随机选取
def Random_integer(N):
    return [random.randint(1, 10) for x in range(N)]
Random_integer(10)

[8, 4, 2, 6, 9, 8, 6, 2, 4, 1]

In [9]:
#4.2
import random
# 导入绘图库，用于绘制趋势图
import matplotlib.pyplot as plt
# 定义函数：生成一个长度为 N 的整数数组，元素在 1 到 10 之间随机选取
def Random_integer(N):
    return [random.randint(1, 10) for x in range(N)]
# 定义函数：计算所有非空子集的平均值之和
def Sum_averages(arr):
    # 初始化子集列表，开始时只有一个空子集
    subsets = [[]]  
    # 初始化总和为 0
    total = 0       
    # 遍历数组中的每个元素
    for num in arr:
        # 用于存储新生成的子集
        new_subsets = []  
        for subset in subsets:
            # 将当前元素加入已有子集，形成新子集
            new_subset = subset + [num] 
            # 添加到新子集列表中
            new_subsets.append(new_subset)  
            # 计算新子集的平均值
            avg = sum(new_subset) / len(new_subset)  
            # 累加到总和中
            total += avg  
        # 将新子集加入原子集列表，继续扩展
        subsets.extend(new_subsets)  
    # 返回所有非空子集平均值的总和
    return total  
arr = Random_integer(10)
result = Sum_averages(arr)
print("随机数组：", arr)
print("所有非空子集平均值之和：", result)

随机数组： [10, 5, 9, 8, 5, 10, 4, 6, 6, 6]
所有非空子集平均值之和： 7058.699999999997


In [ ]:
#4.3
import random
# 导入绘图库，用于绘制趋势图
import matplotlib.pyplot as plt
# 定义函数：生成一个长度为 N 的整数数组，元素在 1 到 10 之间随机选取
def Random_integer(N):
    return [random.randint(1, 100) for x in range(N)]
# 定义函数：计算所有非空子集的平均值之和
def Sum_averages(arr):
    # 初始化子集列表，开始时只有一个空子集
    subsets = [[]]  
    # 初始化总和为 0
    total = 0       
    # 遍历数组中的每个元素
    for num in arr:
        # 用于存储新生成的子集
        new_subsets = []  
        for subset in subsets:
            # 将当前元素加入已有子集，形成新子集
            new_subset = subset + [num] 
            # 添加到新子集列表中
            new_subsets.append(new_subset)  
            # 计算新子集的平均值
            avg = sum(new_subset) / len(new_subset)  
            # 累加到总和中
            total += avg  
        # 将新子集加入原子集列表，继续扩展
        subsets.extend(new_subsets)  
    # 返回所有非空子集平均值的总和
    return total  
# 初始化列表，用于存储每个 N 对应的总平均值
Total_sum_averages = []  
# 从 N = 1 到 N = 100，逐步生成数组并计算 Sum_averages
for N in range(1, 101):
     # 生成长度为 N 的随机数组
    arr = Random_integer(N) 
    # 计算该数组的所有子集平均值之和
    total = Sum_averages(arr)   
    # 将结果添加到列表中
    Total_sum_averages.append(total)  

# 绘制趋势图：X 轴为数组长度 N，Y 轴为 Sum_averages 的值
plt.plot(range(1, 101), Total_sum_averages) # 绘制折线图
plt.xlabel("Array Length N")                # 设置 X 轴标签
plt.ylabel("Sum of Averages")               # 设置 Y 轴标签
plt.title("Growth of Sum_averages with N")  # 设置图表标题
plt.grid(True)                              # 显示网格线
plt.show()                                  # 显示图像

In [10]:
#5.1
import random
import numpy as np
# 创建一个 N 行 M 列的矩阵，左上角和右下角固定为 1，其余位置随机为 0 或 1
def Create_matrix(N, M):
    # 使用列表推导式生成随机矩阵，然后转换为 numpy 数组
    matrix = np.array([[random.randint(0, 1) for x in range(M)] for y in range(N)])
    # 设置左上角为 1（起点）
    matrix[0][0] = 1   
    # 设置右下角为 1（终点）
    matrix[N-1][M-1] = 1   
    # 返回生成的矩阵
    return matrix                 
matrix = Create_matrix(3, 3)
print(matrix)

[[1 1 0]
 [1 1 1]
 [1 0 1]]


In [11]:
#5.2
import random
import numpy as np
# 创建一个 N 行 M 列的矩阵，左上角和右下角固定为 1，其余位置随机为 0 或 1
def Create_matrix(N, M):
    # 使用列表推导式生成随机矩阵，然后转换为 numpy 数组
    matrix = np.array([[random.randint(0, 1) for x in range(M)] for y in range(N)])
    # 设置左上角为 1（起点）
    matrix[0][0] = 1   
    # 设置右下角为 1（终点）
    matrix[N-1][M-1] = 1   
    # 返回生成的矩阵
    return matrix 
# 计算从左上角到右下角的所有合法路径数（只能向右或向下走，且只能走在值为 1 的格子上）
def Count_path(matrix):
    # 获取矩阵的行数和列数
    N, M = len(matrix), len(matrix[0])  
    # 如果起点或终点是障碍（值为 0），直接返回 0 条路径
    if matrix[0][0] == 0 or matrix[N-1][M-1] == 0:
        return 0
    # 初始化路径列表，起点为 (0, 0)
    paths = [[(0, 0)]] 
    # 初始化合法路径计数器
    count = 0                   
    # 使用 while 循环不断扩展路径，直到没有路径可扩展
    while paths:
        # 存储下一轮扩展后的路径
        new_paths = []           
        for path in paths:
            # 获取当前路径的最后一个位置
            i, j = path[-1]      
            # 如果到达终点，计数加一
            if (i, j) == (N - 1, M - 1):
                count += 1
                continue
            # 尝试向右扩展路径
            if j + 1 < M and matrix[i][j + 1] == 1:
                new_paths.append(path + [(i, j + 1)])
            # 尝试向下扩展路径
            if i + 1 < N and matrix[i + 1][j] == 1:
                new_paths.append(path + [(i + 1, j)])
        # 更新当前路径列表为扩展后的路径
        paths = new_paths        
    # 返回合法路径总数
    return count                 
print("矩阵：")
print(matrix)
print("合法路径数：", Count_path(matrix))

矩阵：
[[1 1 0]
 [1 1 1]
 [1 0 1]]
合法路径数： 2


In [12]:
#5.3
import random
import numpy as np
# 创建一个 N 行 M 列的矩阵，左上角和右下角固定为 1，其余位置随机为 0 或 1
def Create_matrix(N, M):
    # 使用列表推导式生成随机矩阵，然后转换为 numpy 数组
    matrix = np.array([[random.randint(0, 1) for x in range(M)] for y in range(N)])
    # 设置左上角为 1（起点）
    matrix[0][0] = 1   
    # 设置右下角为 1（终点）
    matrix[N-1][M-1] = 1   
    # 返回生成的矩阵
    return matrix 
# 计算从左上角到右下角的所有合法路径数（只能向右或向下走，且只能走在值为 1 的格子上）
def Count_path(matrix):
    # 获取矩阵的行数和列数
    N, M = len(matrix), len(matrix[0])  
    # 如果起点或终点是障碍（值为 0），直接返回 0 条路径
    if matrix[0][0] == 0 or matrix[N-1][M-1] == 0:
        return 0
    # 初始化路径列表，起点为 (0, 0)
    paths = [[(0, 0)]] 
    # 初始化合法路径计数器
    count = 0                   
    # 使用 while 循环不断扩展路径，直到没有路径可扩展
    while paths:
        # 存储下一轮扩展后的路径
        new_paths = []           
        for path in paths:
            # 获取当前路径的最后一个位置
            i, j = path[-1]      
            # 如果到达终点，计数加一
            if (i, j) == (N - 1, M - 1):
                count += 1
                continue
            # 尝试向右扩展路径
            if j + 1 < M and matrix[i][j + 1] == 1:
                new_paths.append(path + [(i, j + 1)])
            # 尝试向下扩展路径
            if i + 1 < N and matrix[i + 1][j] == 1:
                new_paths.append(path + [(i + 1, j)])
        # 更新当前路径列表为扩展后的路径
        paths = new_paths        
    # 返回合法路径总数
    return count   
# 设置矩阵大小为 10 行 8 列
N, M = 10, 8
# 设置重复运行次数为 1000
runs = 1000   
# 初始化总路径数
total_paths = 0                 
# 重复运行 1000 次，每次生成新矩阵并计算路径数
for _ in range(runs):
    # 生成随机矩阵
    matrix = Create_matrix(N, M)  
    # 累加路径数
    total_paths += Count_path(matrix)   
# 计算平均路径数
average_paths = total_paths / runs
# 打印结果
print("1000 次运行的平均路径数：", average_paths)


1000 次运行的平均路径数： 0.523
